// TESTES AUTOMATIZADOS

/**TEST DRIVEN DEVELOPMENT -> CRIA O TESTE ANTES DO CÓDIGO ESTAR PRONTO E REFATORA O CÓDIGO DEPOIS
 * BEHAVIOR DRIVEN DEVELOPMENT -> COLOCA REGRAS DE NEGÓCIO AO CÓDIGO
 */

// MOCHA : bdd

